/**
 * Triggers a file download by creating a temporary anchor element.
 */
function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Small delay before revoking so the browser has time to start the download
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Download a blob returned from the bulk-export API.
 */
export function downloadBulkBlob(blob, format) {
  const ext      = format === 'pdf' ? 'pdf' : 'zip';
  const mimeType = format === 'pdf' ? 'application/pdf' : 'application/zip';
  const typed    = new Blob([blob], { type: mimeType });
  triggerDownload(typed, `writegen-export-${Date.now()}.${ext}`);
}

/**
 * Download content as a plain-text .txt file.
 */
export function downloadTxt(item) {
  if (!item?.output) return;
  const blob = new Blob([item.output], { type: 'text/plain;charset=utf-8' });
  triggerDownload(blob, `writegen-${item.type}-${Date.now()}.txt`);
}

/**
 * Build the styled HTML document used for both PDF iframe and direct download.
 */
function buildPdfHtml(item) {
  const title = item.type.replace(/_/g, ' ').toUpperCase();
  // Escape HTML entities to prevent XSS in the generated document
  const escape = (str) =>
    String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${escape(title)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.7;
      color: #1a1a1a;
    }
    header {
      border-bottom: 2px solid #0284c7;
      padding-bottom: 14px;
      margin-bottom: 24px;
    }
    h1 { color: #0284c7; font-size: 1.4rem; margin-bottom: 4px; }
    .meta { font-size: 0.82rem; color: #555; }
    .prompt-box {
      background: #f0f9ff;
      border-left: 4px solid #0284c7;
      padding: 12px 16px;
      border-radius: 4px;
      margin-bottom: 24px;
      font-style: italic;
      color: #374151;
    }
    .content { white-space: pre-wrap; word-wrap: break-word; font-size: 0.95rem; line-height: 1.8; }
    footer {
      margin-top: 40px;
      font-size: 0.75rem;
      color: #9ca3af;
      border-top: 1px solid #e5e7eb;
      padding-top: 12px;
    }
    @media print {
      body { margin: 0; padding: 16px; }
    }
  </style>
</head>
<body>
  <header>
    <h1>✍️ WriteGen AI — ${escape(title)}</h1>
    <div class="meta">
      Tone: ${escape(item.tone)} &nbsp;|&nbsp;
      Words: ${item.wordCount ?? 0} &nbsp;|&nbsp;
      Generated: ${new Date(item.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
    </div>
  </header>
  <div class="prompt-box"><strong>Prompt:</strong> ${escape(item.prompt)}</div>
  <div class="content">${escape(item.output)}</div>
  <footer>Generated by WriteGen AI &nbsp;|&nbsp; writegen.ai</footer>
</body>
</html>`;
}

/**
 * Export content as PDF using a hidden iframe.
 *
 * Why iframe instead of window.open():
 *   - window.open() is blocked as a popup by most browsers unless called
 *     synchronously inside a user-gesture handler.
 *   - A hidden iframe is never treated as a popup and works in all browsers
 *     including Safari, Firefox, and Chrome with strict popup blocking.
 */
export function downloadPdf(item) {
  if (!item?.output) return;

  const html = buildPdfHtml(item);
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url  = URL.createObjectURL(blob);

  const iframe = document.createElement('iframe');
  iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:1px;height:1px;border:none;';
  iframe.src = url;

  iframe.onload = () => {
    try {
      iframe.contentWindow.focus();
      iframe.contentWindow.print();
    } catch {
      // Fallback: open in new tab if iframe print is blocked (e.g. cross-origin)
      window.open(url, '_blank');
    }
    // Clean up after a delay to allow the print dialog to open
    setTimeout(() => {
      document.body.removeChild(iframe);
      URL.revokeObjectURL(url);
    }, 60_000);
  };

  document.body.appendChild(iframe);
}
